let calcularTemperaturaMedia = (temperaturaMaxima, temperaturaMinima) => (temperaturaMaxima + temperaturaMinima) / 2
let temperaturaMaximaD1 = 30; 
let  temperaturaMinimaD1 = 15;
let temperaturaMediaD1 = calcularTemperaturaMedia(temperaturaMaximaD1, temperaturaMinimaD1);
console.log(`La temperatura media del día 1 es: ${temperaturaMediaD1}`);
let temperaturaMaximaD2 = 40; 
let  temperaturaMinimaD2 = 95;
let temperaturaMediaD2 = calcularTemperaturaMedia(temperaturaMaximaD2, temperaturaMinimaD2);
console.log(`La temperatura media del día 2 es: ${temperaturaMediaD2}`);
let temperaturaMaximaD3 = 10; 
let  temperaturaMinimaD3 = 67;
let temperaturaMediaD3 = calcularTemperaturaMedia(temperaturaMaximaD3, temperaturaMinimaD3);
console.log(`La temperatura media del día 3 es: ${temperaturaMediaD3}`);
let temperaturaMaximaD4 = 7; 
let  temperaturaMinimaD4 = 30;
let temperaturaMediaD4 = calcularTemperaturaMedia(temperaturaMaximaD4, temperaturaMinimaD4);
console.log(`La temperatura media del día 4 es: ${temperaturaMediaD4}`);
let temperaturaMaximaD5 = 5; 
let  temperaturaMinimaD5 = 35;
let temperaturaMediaD5 = calcularTemperaturaMedia(temperaturaMaximaD5, temperaturaMinimaD5);
console.log(`La temperatura media del día 5 es: ${temperaturaMediaD5}`);
let temperaturaMaximaD6 = 12; 
let  temperaturaMinimaD6 = 9;
let temperaturaMediaD6 = calcularTemperaturaMedia(temperaturaMaximaD6, temperaturaMinimaD6);
console.log(`La temperatura media del día 6 es: ${temperaturaMediaD6}`);
let temperaturaMaximaD7 = 70; 
let  temperaturaMinimaD7 = 38;
let temperaturaMediaD7 = calcularTemperaturaMedia(temperaturaMaximaD7, temperaturaMinimaD7);
console.log(`La temperatura media del día 7 es: ${temperaturaMediaD7}`);